# Generated by Django 3.2.13 on 2022-10-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Action', 'Action'), ('Romance', 'Romance'), ('Adventure', 'Adventure'), ('Crime', 'Crime'), ('War', 'War'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Science Fiction ', 'Science Fiction '), ('Musicals', 'Musicals'), ('Historical', 'Historical')], max_length=20),
        ),
    ]
